export enum AndroidViewFlag {
    SYSTEM_UI_FLAG_LAYOUT_STABLE = 256,
    SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION = 512,
    SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN = 1024,
    SYSTEM_UI_FLAG_HIDE_NAVIGATION = 2,
    SYSTEM_UI_FLAG_FULLSCREEN = 4,
    SYSTEM_UI_FLAG_IMMERSIVE_STICKY = 4096
}